name: Main CI

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    environment: tests

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.9

      - name: install depends
        run: |
          python -m pip install --upgrade pip

      - name: install poetry
        run: |
          pip install poetry

      - name: install project
        run: |
          poetry install

      - name: run tests
        run:
          poetry run pytest

